// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storyboard.Infrastructure.Persistence;

#nullable disable

namespace Storyboard.Migrations
{
    [DbContext(typeof(StoryboardDbContext))]
    [Migration("20260118012518_AddCreativeIntentToProject")]
    partial class AddCreativeIntentToProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Storyboard.Domain.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreativeGoal")
                        .HasColumnType("TEXT");

                    b.Property<double>("DetectionSensitivity")
                        .HasColumnType("REAL");

                    b.Property<int>("ExtractModeIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrameCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasVideoFile")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedVideoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeInterval")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoFileDuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoFileFps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoFileResolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoTone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Storyboard.Domain.Entities.Shot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CameraFixed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CameraMovement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Composition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoreContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<double>("EndTime")
                        .HasColumnType("REAL");

                    b.Property<string>("FirstFrameAspectRatio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstFrameColorStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstFrameComposition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstFrameImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstFrameImageSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstFrameLensType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstFrameLightingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstFrameNegativePrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstFramePrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstFrameSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstFrameSelectedModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstFrameTimeOfDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedVideoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFrameAspectRatio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFrameColorStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFrameComposition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFrameImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFrameImageSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFrameLensType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFrameLightingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFrameNegativePrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFramePrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastFrameSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastFrameSelectedModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFrameTimeOfDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LensType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LightingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialBrightness")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialColorTone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialFileSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialResolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("NegativePrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SceneSettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShootingStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShotNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShotType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StartTime")
                        .HasColumnType("REAL");

                    b.Property<string>("StyleDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseFirstFrameReference")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseLastFrameReference")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoEffect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VideoFrames")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoNegativePrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoRatio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoResolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Watermark")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "ShotNumber")
                        .IsUnique();

                    b.ToTable("Shots", (string)null);
                });

            modelBuilder.Entity("Storyboard.Domain.Entities.ShotAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ShotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoThumbnailPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShotId");

                    b.HasIndex("ProjectId", "ShotId", "Type");

                    b.ToTable("ShotAssets", (string)null);
                });

            modelBuilder.Entity("Storyboard.Domain.Entities.Shot", b =>
                {
                    b.HasOne("Storyboard.Domain.Entities.Project", "Project")
                        .WithMany("Shots")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Storyboard.Domain.Entities.ShotAsset", b =>
                {
                    b.HasOne("Storyboard.Domain.Entities.Shot", "Shot")
                        .WithMany("Assets")
                        .HasForeignKey("ShotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shot");
                });

            modelBuilder.Entity("Storyboard.Domain.Entities.Project", b =>
                {
                    b.Navigation("Shots");
                });

            modelBuilder.Entity("Storyboard.Domain.Entities.Shot", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
