-- 增量迁移：添加 AI 解析字段到 Shots 表
-- 此脚本是幂等的，可以安全地多次运行

-- 图片生成参数
ALTER TABLE Shots ADD COLUMN ImageSize TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN NegativePrompt TEXT NOT NULL DEFAULT '';

-- 图片专业参数
ALTER TABLE Shots ADD COLUMN AspectRatio TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN LightingType TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN TimeOfDay TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN Composition TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN ColorStyle TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN LensType TEXT NOT NULL DEFAULT '';

-- 视频生成参数
ALTER TABLE Shots ADD COLUMN VideoPrompt TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN SceneDescription TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN ActionDescription TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN StyleDescription TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN VideoNegativePrompt TEXT NOT NULL DEFAULT '';

-- 视频专业参数
ALTER TABLE Shots ADD COLUMN CameraMovement TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN ShootingStyle TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN VideoEffect TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN VideoResolution TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN VideoRatio TEXT NOT NULL DEFAULT '';
ALTER TABLE Shots ADD COLUMN VideoFrames INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Shots ADD COLUMN UseFirstFrameReference INTEGER NOT NULL DEFAULT 1;
ALTER TABLE Shots ADD COLUMN UseLastFrameReference INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Shots ADD COLUMN Seed INTEGER;
ALTER TABLE Shots ADD COLUMN CameraFixed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Shots ADD COLUMN Watermark INTEGER NOT NULL DEFAULT 0;
